<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- ========================================================= -->
    <!-- Project Information                                       -->
    <!-- ========================================================= -->

    <groupId>br.edu.esuda</groupId>
    <artifactId>laboratorio-race-condition</artifactId>
    <version>1.0.1</version>
    <packaging>jar</packaging>

    <name>Laboratório Race Condition</name>

    <description>
        Java Concurrency Laboratory - Race Condition and Synchronization
    </description>

    <!-- ========================================================= -->
    <!-- Properties                                                -->
    <!-- ========================================================= -->

    <properties>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <maven.compiler.release>17</maven.compiler.release>

    </properties>

    <!-- ========================================================= -->
    <!-- Dependencies                                              -->
    <!-- ========================================================= -->

    <dependencies>

        <!--
            No external dependencies are required.
            This project uses only the Java Standard Library.
        -->

    </dependencies>

    <!-- ========================================================= -->
    <!-- Build                                                     -->
    <!-- ========================================================= -->

    <build>

        <plugins>

            <!-- Java Compiler -->
            <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>

                <configuration>

                    <release>17</release>

                </configuration>

            </plugin>

            <!-- Executable JAR -->

            <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.2</version>

                <configuration>

                    <archive>

                        <manifest>

                            <mainClass>
                                br.edu.esuda.concurrent.Main
                            </mainClass>

                        </manifest>

                    </archive>

                </configuration>

            </plugin>

        </plugins>

    </build>

</project>
